"""
crud/prayer_requests.py — Supabase REST calls for prayer_requests table.

What it does:
  All database I/O for prayer requests: create, list (filtered by status),
  fetch single, and moderate (approve/reject with audit metadata).

Why it exists at this layer:
  Isolating Supabase calls keeps routers thin and every DB interaction
  independently patchable in tests.

How it connects:
  - app/routers/prayer_requests.py calls these functions.
  - tests/test_prayer_requests.py patches these via unittest.mock.patch.
  - app/config.py supplies supabase_url, supabase_service_key, church_id.

Schema notes:
  - id: UUID with DB default — Supabase generates it, we don't pass it on insert
  - body: the prayer text
  - ai_score / ai_reason: AI moderation result stored for audit
  - moderated_at / moderated_by: staff audit trail
  - approved_at is not a column — we use moderated_at for that

Status values: 'pending' | 'approved' | 'rejected'
"""

from datetime import datetime, timezone

import httpx

from app.config import settings
from app.schemas.prayer_request import PrayerRequestCreate, PrayerRequestModerate


def _headers() -> dict:
    return {
        "apikey":        settings.supabase_service_key,
        "Authorization": f"Bearer {settings.supabase_service_key}",
        "Content-Type":  "application/json",
        "Prefer":        "return=representation",
    }


def _base_url() -> str:
    return f"{settings.supabase_url}/rest/v1/prayer_requests"


def create_prayer_request(
    payload: PrayerRequestCreate,
    church_id: str,
    ai_approved: bool,
    ai_score: float | None = None,
    ai_reason: str | None = None,
) -> dict:
    """
    Insert a new prayer request.

    `ai_approved` determines whether status is 'approved' or 'rejected'.
    The submitter always receives 201 — they don't learn if rejected.
    id is generated by the DB (UUID default).
    """
    status = "approved" if ai_approved else "rejected"
    row = {
        "church_id":    church_id,
        "body":         payload.body,
        "name":         payload.name,
        "email":        payload.email,
        "is_anonymous": payload.is_anonymous,
        "status":       status,
        "ai_score":     ai_score,
        "ai_reason":    ai_reason if not ai_approved else None,
    }
    resp = httpx.post(_base_url(), json=row, headers=_headers())
    resp.raise_for_status()
    data = resp.json()
    return data[0] if isinstance(data, list) else data


def list_prayer_requests(status: str = "approved", church_id: str = "") -> list[dict]:
    """
    Fetch prayer requests filtered by status.

    - status='approved' → member-facing list
    - status='pending'  → staff moderation queue
    - status='rejected' → admin audit trail

    Returns [] when church_id is not configured (same guard as sermons/events).
    """
    cid = church_id or settings.church_id
    if not cid:
        return []

    params = {
        "church_id": f"eq.{cid}",
        "status":    f"eq.{status}",
        "order":     "submitted_at.desc",
        "select":    "*",
    }
    resp = httpx.get(_base_url(), headers=_headers(), params=params)
    resp.raise_for_status()
    return resp.json()


def get_prayer_request(prayer_id: str) -> dict | None:
    """Fetch a single prayer request by UUID. Returns None if not found."""
    params = {"id": f"eq.{prayer_id}", "select": "*"}
    resp = httpx.get(_base_url(), headers=_headers(), params=params)
    resp.raise_for_status()
    data = resp.json()
    return data[0] if data else None


def moderate_prayer_request(
    prayer_id: str,
    payload: PrayerRequestModerate,
    moderator_id: str,
) -> dict:
    """
    Staff approves or rejects a prayer request.
    Records moderator UUID and timestamp in moderated_at / moderated_by.
    """
    now = datetime.now(timezone.utc).isoformat()
    update = {
        "status":       payload.status,
        "moderated_at": now,
        "moderated_by": moderator_id,
        "ai_reason":    payload.reason if payload.status == "rejected" else None,
        "updated_at":   now,
    }
    params = {"id": f"eq.{prayer_id}"}
    resp = httpx.patch(_base_url(), json=update, headers=_headers(), params=params)
    resp.raise_for_status()
    data = resp.json()
    return data[0] if isinstance(data, list) else data
